// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package database

import (
	"context"
)

const getOrCreateChat = `-- name: GetOrCreateChat :one
WITH upsert_chat AS (
    INSERT INTO chat (chat_id, type)
    VALUES ($1, $2)
    ON CONFLICT (chat_id) DO NOTHING
    RETURNING chat_id, type, created_at, updated_at
),
upsert_settings AS (
    INSERT INTO settings (chat_id, language, captions, silent, nsfw, media_album_limit, delete_processed)
    VALUES ($1, $3, $4, $5, $6, $7, FALSE)
    ON CONFLICT (chat_id) DO UPDATE SET
        language = CASE 
            WHEN settings.language = 'XX' THEN EXCLUDED.language 
            ELSE settings.language 
        END
    RETURNING chat_id, nsfw, media_album_limit, captions, silent, language, created_at, updated_at, disabled_extractors, delete_processed
),
final_chat AS (
    SELECT chat_id, type, created_at, updated_at FROM upsert_chat
    UNION ALL
    SELECT chat_id, type, created_at, updated_at FROM chat WHERE chat_id = $1 AND NOT EXISTS (SELECT 1 FROM upsert_chat)
),
final_settings AS (
    SELECT chat_id, nsfw, media_album_limit, captions, silent, language, created_at, updated_at, disabled_extractors, delete_processed FROM upsert_settings
)
SELECT 
    c.chat_id,
    c.type,
    s.nsfw,
    s.media_album_limit,
    s.captions,
    s.silent,
    s.language,
    s.disabled_extractors,
    s.delete_processed
FROM final_chat c 
JOIN final_settings s ON s.chat_id = c.chat_id
`

type GetOrCreateChatParams struct {
	ChatID          int64
	Type            ChatType
	Language        string
	Captions        bool
	Silent          bool
	Nsfw            bool
	MediaAlbumLimit int32
}

type GetOrCreateChatRow struct {
	ChatID             int64
	Type               ChatType
	Nsfw               bool
	MediaAlbumLimit    int32
	Captions           bool
	Silent             bool
	Language           string
	DisabledExtractors []string
	DeleteProcessed    bool
}

func (q *Queries) GetOrCreateChat(ctx context.Context, arg GetOrCreateChatParams) (GetOrCreateChatRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateChat,
		arg.ChatID,
		arg.Type,
		arg.Language,
		arg.Captions,
		arg.Silent,
		arg.Nsfw,
		arg.MediaAlbumLimit,
	)
	var i GetOrCreateChatRow
	err := row.Scan(
		&i.ChatID,
		&i.Type,
		&i.Nsfw,
		&i.MediaAlbumLimit,
		&i.Captions,
		&i.Silent,
		&i.Language,
		&i.DisabledExtractors,
		&i.DeleteProcessed,
	)
	return i, err
}
