// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: errors.sql

package database

import (
	"context"
)

const getErrorByID = `-- name: GetErrorByID :one
SELECT message
FROM errors
WHERE id = $1
`

func (q *Queries) GetErrorByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getErrorByID, id)
	var message string
	err := row.Scan(&message)
	return message, err
}

const logError = `-- name: LogError :exec
INSERT INTO errors (id, message)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET occurrences = errors.occurrences + 1,
    last_seen = NOW()
`

type LogErrorParams struct {
	ID      string
	Message string
}

func (q *Queries) LogError(ctx context.Context, arg LogErrorParams) error {
	_, err := q.db.Exec(ctx, logError, arg.ID, arg.Message)
	return err
}
