// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatType string

const (
	ChatTypePrivate ChatType = "private"
	ChatTypeGroup   ChatType = "group"
)

func (e *ChatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatType(s)
	case string:
		*e = ChatType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatType: %T", src)
	}
	return nil
}

type NullChatType struct {
	ChatType ChatType
	Valid    bool // Valid is true if ChatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatType), nil
}

type MediaCodec string

const (
	MediaCodecAvc    MediaCodec = "avc"
	MediaCodecHevc   MediaCodec = "hevc"
	MediaCodecVp9    MediaCodec = "vp9"
	MediaCodecVp8    MediaCodec = "vp8"
	MediaCodecAv1    MediaCodec = "av1"
	MediaCodecWebp   MediaCodec = "webp"
	MediaCodecAac    MediaCodec = "aac"
	MediaCodecOpus   MediaCodec = "opus"
	MediaCodecVorbis MediaCodec = "vorbis"
	MediaCodecMp3    MediaCodec = "mp3"
	MediaCodecFlac   MediaCodec = "flac"
)

func (e *MediaCodec) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaCodec(s)
	case string:
		*e = MediaCodec(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaCodec: %T", src)
	}
	return nil
}

type NullMediaCodec struct {
	MediaCodec MediaCodec
	Valid      bool // Valid is true if MediaCodec is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaCodec) Scan(value interface{}) error {
	if value == nil {
		ns.MediaCodec, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaCodec.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaCodec) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaCodec), nil
}

type MediaType string

const (
	MediaTypePhoto MediaType = "photo"
	MediaTypeVideo MediaType = "video"
	MediaTypeAudio MediaType = "audio"
)

func (e *MediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaType(s)
	case string:
		*e = MediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaType: %T", src)
	}
	return nil
}

type NullMediaType struct {
	MediaType MediaType
	Valid     bool // Valid is true if MediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaType), nil
}

type Chat struct {
	ChatID    int64
	Type      ChatType
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Errors struct {
	ID          string
	Message     string
	Occurrences int32
	FirstSeen   pgtype.Timestamp
	LastSeen    pgtype.Timestamp
}

type Media struct {
	ID          int64
	ContentID   string
	ContentUrl  string
	ExtractorID string
	Caption     pgtype.Text
	Nsfw        bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type MediaFormat struct {
	FormatID   string
	ItemID     int64
	FileID     string
	Type       MediaType
	AudioCodec NullMediaCodec
	VideoCodec NullMediaCodec
	Duration   pgtype.Int4
	Title      pgtype.Text
	Artist     pgtype.Text
	Width      pgtype.Int4
	Height     pgtype.Int4
	Bitrate    pgtype.Int8
	FileSize   pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type MediaItem struct {
	ID        int64
	MediaID   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Settings struct {
	ChatID             int64
	Nsfw               bool
	MediaAlbumLimit    int32
	Captions           bool
	Silent             bool
	Language           string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DisabledExtractors []string
	DeleteLinks        bool
}
