// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package database

import (
	"context"
)

const addDisabledExtractor = `-- name: AddDisabledExtractor :exec
UPDATE settings
SET disabled_extractors = array_append(disabled_extractors, $1), updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $2
AND NOT ($1 = ANY(disabled_extractors))
`

type AddDisabledExtractorParams struct {
	ExtractorID interface{}
	ChatID      int64
}

func (q *Queries) AddDisabledExtractor(ctx context.Context, arg AddDisabledExtractorParams) error {
	_, err := q.db.Exec(ctx, addDisabledExtractor, arg.ExtractorID, arg.ChatID)
	return err
}

const removeDisabledExtractor = `-- name: RemoveDisabledExtractor :exec
UPDATE settings
SET disabled_extractors = array_remove(disabled_extractors, $1), updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $2
`

type RemoveDisabledExtractorParams struct {
	ExtractorID interface{}
	ChatID      int64
}

func (q *Queries) RemoveDisabledExtractor(ctx context.Context, arg RemoveDisabledExtractorParams) error {
	_, err := q.db.Exec(ctx, removeDisabledExtractor, arg.ExtractorID, arg.ChatID)
	return err
}

const setChatLanguage = `-- name: SetChatLanguage :exec
UPDATE settings
SET language = $1, updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $2
`

type SetChatLanguageParams struct {
	Language string
	ChatID   int64
}

func (q *Queries) SetChatLanguage(ctx context.Context, arg SetChatLanguageParams) error {
	_, err := q.db.Exec(ctx, setChatLanguage, arg.Language, arg.ChatID)
	return err
}

const setChatMediaAlbumLimit = `-- name: SetChatMediaAlbumLimit :exec
UPDATE settings
SET media_album_limit = $1, updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $2
`

type SetChatMediaAlbumLimitParams struct {
	MediaAlbumLimit int32
	ChatID          int64
}

func (q *Queries) SetChatMediaAlbumLimit(ctx context.Context, arg SetChatMediaAlbumLimitParams) error {
	_, err := q.db.Exec(ctx, setChatMediaAlbumLimit, arg.MediaAlbumLimit, arg.ChatID)
	return err
}

const toggleChatCaptions = `-- name: ToggleChatCaptions :exec
UPDATE settings
SET captions = NOT captions, updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $1
`

func (q *Queries) ToggleChatCaptions(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, toggleChatCaptions, chatID)
	return err
}

const toggleChatDeleteLinks = `-- name: ToggleChatDeleteLinks :exec
UPDATE settings
SET delete_links = NOT delete_links, updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $1
`

func (q *Queries) ToggleChatDeleteLinks(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, toggleChatDeleteLinks, chatID)
	return err
}

const toggleChatNsfw = `-- name: ToggleChatNsfw :exec
UPDATE settings
SET nsfw = NOT nsfw, updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $1
`

func (q *Queries) ToggleChatNsfw(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, toggleChatNsfw, chatID)
	return err
}

const toggleChatSilentMode = `-- name: ToggleChatSilentMode :exec
UPDATE settings
SET silent = NOT silent, updated_at = CURRENT_TIMESTAMP
WHERE chat_id = $1
`

func (q *Queries) ToggleChatSilentMode(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, toggleChatSilentMode, chatID)
	return err
}
