version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - goheader
    - goprintffuncname
    - grouper
    - iface
    - importas
    - interfacebloat
    - intrange
    - mirror
    - nilerr
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - unconvert
    - usestdlibvars
    - wastedassign
  disable:
    - errcheck